### ISSUE TITLE
Silently does not perform destructive migrations

### ISSUE THREAD

**Issue by turion** [jumpn/ecto_cockroachdb#2]
Follow-up of https://github.com/elixir-ecto/ecto_sql/issues/144.

Let's assume I write the following migration:

```
defmodule Repo.Migrations.Test do
  use Ecto.Migration

  def up do
    create table("test") do
      add :test, :integer
    end
    flush()
    rename table("test"), :test, to: :test2
    flush()
    alter table("test") do
      add :test, :integer
    end
  end

  def down do
    alter table("test") do
      remove :test
    end
    flush()
    rename table("test"), :test2, to: :test
    flush()
    drop table("test")
  end
end
```
I can run it up:

```
$ mix ecto.migrate --to=20190916150901 --log-sql=true
15:15:44.462 [info]  == Running 20190916150901 Repo.Migrations.Test.up/0 forward

15:15:44.462 [info]  create table test

15:15:44.471 [debug] QUERY OK db=8.5ms
CREATE TABLE "test" ("id" bigserial, "test" integer, PRIMARY KEY ("id")) []

15:15:44.471 [info]  rename column test to test2 on table test

15:15:44.474 [debug] QUERY OK db=2.2ms
ALTER TABLE "test" RENAME "test" TO "test2" []

15:15:44.474 [info]  alter table test

15:15:44.481 [debug] QUERY OK db=7.3ms
ALTER TABLE "test" ADD COLUMN "test" integer []

15:15:44.483 [info]  == Migrated 20190916150901 in 0.0s
```
But rollback fails:
```
$ mix ecto.rollback --log-sql=true
15:16:08.352 [info]  == Running 20190916150901 Repo.Migrations.Test.down/0 forward

15:16:08.353 [info]  alter table test

15:16:08.356 [debug] QUERY OK db=2.5ms
ALTER TABLE "test" DROP COLUMN "test" []

15:16:08.356 [info]  rename column test2 to test on table test

15:16:08.378 [debug] QUERY ERROR db=21.8ms
ALTER TABLE "test" RENAME "test2" TO "test" []
** (Postgrex.Error) ERROR XX000 (internal_error) column name "test" already exists
    (ecto_sql) lib/ecto/adapters/sql.ex:621: Ecto.Adapters.SQL.raise_sql_call_error/1
    (elixir) lib/enum.ex:1336: Enum."-map/2-lists^map/1-0-"/2
    (ecto_sql) lib/ecto/adapters/sql.ex:708: Ecto.Adapters.SQL.execute_ddl/4
    (ecto_sql) lib/ecto/migration/runner.ex:340: Ecto.Migration.Runner.log_and_execute_ddl/3
    (ecto_sql) lib/ecto/migration/runner.ex:119: anonymous fn/6 in Ecto.Migration.Runner.flush/0
    (elixir) lib/enum.ex:1948: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto_sql) lib/ecto/migration/runner.ex:118: Ecto.Migration.Runner.flush/0
    priv/repo/migrations/20190916150901_test.exs:24: Repo.Migrations.Test.down/0
```
Running the commands in a Cockroach prompt seems to reveal the cause:
```
#
root@127.0.0.1:26257/defaultdb> CREATE TABLE "test" ("id" bigserial, "test" integer, PRIMARY KEY ("id"));
CREATE TABLE

Time: 24.086524ms

root@127.0.0.1:26257/defaultdb> ALTER TABLE "test" RENAME "test" TO "test2";
RENAME COLUMN

Time: 48.405945ms

root@127.0.0.1:26257/defaultdb> ALTER TABLE "test" ADD COLUMN "test" integer;
ALTER TABLE

Time: 157.332251ms

root@127.0.0.1:26257/defaultdb> ALTER TABLE "test" DROP COLUMN "test";
pq: rejected: ALTER TABLE DROP COLUMN will remove all data in that column (sql_safe_updates = true)
root@127.0.0.1:26257/defaultdb> ALTER TABLE "test" RENAME "test2" TO "test";
pq: column name "test" already exists
```

So already in the `DROP COLUMN` statement, there is an error. I find it strange that this error is not rethrown through ecto, but the second one is.

Here is what happens if I switch safe updates off:

```
root@127.0.0.1:26257/defaultdb> SET sql_safe_updates = FALSE;
SET

Time: 876.383µs

root@127.0.0.1:26257/defaultdb> drop table "test";
DROP TABLE

Time: 79.801373ms

root@127.0.0.1:26257/defaultdb> CREATE TABLE "test" ("id" bigserial, "test" integer, PRIMARY KEY ("id"));
CREATE TABLE

Time: 23.327178ms

root@127.0.0.1:26257/defaultdb> ALTER TABLE "test" RENAME "test" TO "test2";
RENAME COLUMN

Time: 33.827897ms

root@127.0.0.1:26257/defaultdb> ALTER TABLE "test" ADD COLUMN "test" integer;
ALTER TABLE

Time: 138.131865ms

root@127.0.0.1:26257/defaultdb> ALTER TABLE "test" DROP COLUMN "test";
ALTER TABLE

Time: 216.117307ms

root@127.0.0.1:26257/defaultdb> ALTER TABLE "test" RENAME "test2" TO "test";
RENAME COLUMN

Time: 116.083427ms
```

So the two problems here are:

* Safe updates are switched off by default, but they should be allowed in some cases
* The first error message is not propagated

**Comment by turion** [comment]
I can't even find a workaround. Adding e.g. `execute "SET sql_safe_updates = FALSE"` does not help, and I don't understand why.

**Comment by tlvenn** [comment]
I believe this is in the same category of issues as #1 and you should report this with CDB directly, thanks in advance.

**Comment by tlvenn** [comment]
Btw you might want to try if you can reproduce this with the latest CDB 19.2 alpha.

**Comment by turion** [comment]
I don't see how it is similar to the issue you mentioned. When I perform the commands emitted by the ecto adapter manually, everything works fine.

**Comment by tlvenn** [comment]
Using the same transaction boundaries ? CDB had/has known issues when you try to manipulate the schema and operate on it within the same TX, that is why I assumed it was related.

**Comment by tlvenn** [comment]
In your example above using the CDB cli, once you have switched safe updates off, do start a transaction before issuing the commands and commit at the end, I am fairly sure you will reproduce the error.

**Comment by turion** [comment]
> In your example above using the CDB cli, once you have switched safe updates off, do start a transaction before issuing the command and commit at the end, I am fairly sure you will reproduce the error.

Yes, but isn't that what `flush/0` is for?

**Comment by turion** [comment]
I agree that Cockroach should handle this better, and I opened https://github.com/cockroachdb/cockroach/issues/40862 for that. But still, I think `flush/0` is there to work around such limitations.
