### ISSUE TITLE
Ecto.Adapters.CockroachDB.lock_for_migrations/3 is undefined or private - workaround

### ISSUE THREAD

**Issue by cdesch** [jumpn/ecto_cockroachdb#5]
When migrating with `mix ecto.migrate`, I get this error:

```
cjsMBP15:ex_brewery cj1$ mix ecto.migrate
** (UndefinedFunctionError) function Ecto.Adapters.CockroachDB.lock_for_migrations/3 is undefined or private
    (ecto_cockroachdb 1.0.0) Ecto.Adapters.CockroachDB.lock_for_migrations(%{cache: #Reference<0.441031426.2735341571.16122>, opts: [timeout: 15000, pool_size: 2, pool: DBConnection.ConnectionPool], pid: #PID<0.298.0>, repo: ExBrewery.Repo, sql: Ecto.Adapters.CockroachDB.Connection, telemetry: {ExBrewery.Repo, :debug, [:ex_brewery, :repo, :query]}}, [log: false, migration_source: "schema_migrations", all: true], #Function<13.87708295/0 in Ecto.Migrator.lock_for_migrations/4>)
    (ecto_sql 3.7.1) lib/ecto/migrator.ex:526: Ecto.Migrator.lock_for_migrations/4
    (ecto_sql 3.7.1) lib/ecto/migrator.ex:419: Ecto.Migrator.run/4
    (ecto_sql 3.7.1) lib/ecto/migrator.ex:146: Ecto.Migrator.with_repo/3
    (ecto_sql 3.7.1) lib/mix/tasks/ecto.migrate.ex:138: anonymous fn/5 in Mix.Tasks.Ecto.Migrate.run/2
    (elixir 1.12.3) lib/enum.ex:2385: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto_sql 3.7.1) lib/mix/tasks/ecto.migrate.ex:126: Mix.Tasks.Ecto.Migrate.run/2
    (mix 1.12.3) lib/mix/task.ex:394: anonymous fn/3 in Mix.Task.run_task/3
```

I think this is somewhat expected as the [docs say](https://github.com/jumpn/ecto_cockroachdb/blob/d7b3bf9b5e7e2e86f438aabb15df975dc695be48/README.md?plain=1#L12) "It also disable the migration lock given locking is not supported by CockroachDB either."

How should we migrate databases then? Is this migration feature completely disabled or can the locking during migration be disabled?

**Comment by tlvenn** [comment]
Hi @cdesch,

You don't need this small fork anymore as CDB 20.1+ supports optional timestamp precision.
So just use the oob postgrer adaptor and just make sure to disable locking in your repo config with:

`migration_lock: nil`
